### ISSUE TITLE
/docs/usage/cli.md

### ISSUE THREAD

**Issue by QC-L** [docschina/babeljs.io#11]

**Comment by foryuki** [comment]
此章节由我翻译，翻译时间为 2017.11.13-2017.11.14

**Comment by foryuki** [comment]
此章节我已翻译完成。见 PR https://github.com/docschina/babeljs.io/pull/109

**Comment by hijiangtao** [comment]
此章节由我校对，校对时间为 2017.12.11-2017.12.12

**Comment by hijiangtao** [comment]
校对完成，见 PR #166
