### ISSUE TITLE
/docs/core-packages.md

### ISSUE THREAD

**Issue by QC-L** [docschina/babeljs.io#18]
翻译该文档，还需翻译 /_includes/readmes/babel-core.md

**Comment by aprildove** [comment]
此章节由我翻译 11.9 — 11.23

**Comment by aprildove** [comment]
翻译完成 #130

**Comment by aprildove** [comment]
babel-core.md 没看到，也要翻译。。遗漏了。。 正在翻译ing

**Comment by hijiangtao** [comment]
此章节由我校对，校对时间为 2017.12.13-2017.12.14

**Comment by hijiangtao** [comment]
校对完成，见 PR #168
