### ISSUE TITLE
/_includes/tools/browser

### ISSUE THREAD

**Issue by QC-L** [docschina/babeljs.io#22]
文件夹下 md 文件均翻译

**Comment by QC-L** [comment]
此章节由我翻译，翻译时间为 2017.11.03-2017.11.04

**Comment by QC-L** [comment]
此章节由我翻译，翻译时间为 2017.11.03-2017.11.04

**Comment by QC-L** [comment]
此章节我已翻译完成。见 PR #23

**Comment by hijiangtao** [comment]
此章节由我校对，校对时间为 2017.12.14-2017.12.15

**Comment by hijiangtao** [comment]
已完成校对，见 PR #171
